### ISSUE TITLE
Outlookカレンダー連携テスト

### ISSUE THREAD

**Issue by nitamagoGoGo** [kenta-afk/phase4-Product#2]

**Comment by KOU050223** [comment]
Outlook関係のAPIについて
https://learn.microsoft.com/ja-jp/outlook/rest/

**Comment by KOU050223** [comment]
Microsoft Graph PHP SDK を使用するため以下のコマンドを実行する
```bash
composer clear-cache
composer install
```

**Comment by KOU050223** [comment]
必要な機能
- カレンダーに会議室がどの時間に使用されるかを登録
- カレンダーから会議室がどの時間に使用されているかを参照
- 日時が変更された際にカレンダーの予定に変更を加える
- 予定を削除する

**Comment by KOU050223** [comment]
OutlookAPIを使用するにはAzureでアプリの登録をしないといけない
Azureアカウントについて要相談

**Comment by KOU050223** [comment]
カレンダーに追加
https://learn.microsoft.com/ja-jp/graph/outlook-calendar-online-meetings?tabs=http

**Comment by KOU050223** [comment]
env読み込まれないとき
https://qiita.com/itoh28/items/718ba13bd6bde7b8a235

**Comment by KOU050223** [comment]
もし特定のカレンダー（例：共有カレンダーや複数のカレンダーの中から選択したカレンダー）からのみイベントを取得したい場合は、そのカレンダーのIDを使用して/me/calendars/{calendar-id}/events エンドポイントを呼び出す必要があります。

**Comment by KOU050223** [comment]
web版のOutlookカレンダーを見たらちゃんと入ってました
